// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_content_delivery_bucket": "slingshot-app-20200326111218-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "eu-west-2",
    "aws_content_delivery_url": "http://slingshot-app-20200326111218-hostingbucket-dev.s3-website.eu-west-2.amazonaws.com",
    "aws_cognito_identity_pool_id": "eu-west-2:d4052652-3df3-4f38-aa93-d0e8ee4dd84c",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_c1Ex6hlbe",
    "aws_user_pools_web_client_id": "4cisl30h2mdngmjrh7jdeqjp6u",
    "oauth": {}
};


export default awsmobile;
